CREATE TABLE estimates (
    id VARCHAR(255) PRIMARY KEY,
    tenant_id VARCHAR(255),
    estimate_number VARCHAR(255),
    revision_number VARCHAR(255),
    business_service VARCHAR(255),
    project_id VARCHAR(255),
    proposal_date DECIMAL,
    status VARCHAR(50),
    wf_status VARCHAR(50),
    name VARCHAR(255),
    reference_number VARCHAR(255),
    description TEXT,
    executing_department VARCHAR(255),
    total_estimate_amount DECIMAL,
    additional_details JSONB,
    createdBy character varying(64),
    lastModifiedBy character varying(64),
    createdTime bigint,
    lastModifiedTime bigint
);

--CREATE TABLE addresses (
--    id VARCHAR(255) PRIMARY KEY,
--    estimate_id VARCHAR(255),
--    tenant_id VARCHAR(255),
--    door_no VARCHAR(255),
--    latitude NUMERIC,
--    longitude NUMERIC,
--    address_number VARCHAR(255),
--    type VARCHAR(255),
--    address_line1 VARCHAR(255),
--    address_line2 VARCHAR(255),
--    landmark VARCHAR(255),
--    city VARCHAR(255),
--    pincode VARCHAR(255),
--    detail VARCHAR(255),
--    building_name VARCHAR(255),
--    street VARCHAR(255),
--    boundary_code VARCHAR(255),
--    boundary_name VARCHAR(255),
--    boundary_label VARCHAR(255),
--    boundary_latitude VARCHAR(255),
--    boundary_longitude VARCHAR(255),
--    boundary_children JSONB,
--    boundary_materializedPath VARCHAR(255),
--    boundary_type VARCHAR(255),
--    FOREIGN KEY (estimate_id) REFERENCES estimates(id)
--);


